name: wordle_ui
description: Wordle UI library
version: 0.0.1

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_gen: ^4.3.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_gen_runner: ^4.3.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
flutter_gen:
  output: lib/gen/ 
  line_length: 80 

flutter:
  assets:
    - assets/